[project]
name = "largrect"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = [
    "numpy",
]

[build-system]
requires = [
    "setuptools",
    "numpy",
]
build-backend = "setuptools.build_meta"
